version: '3.8'

services:

      sprintpoker-springboot-container:
            image: java-docker
            build:
                  context: .
                  dockerfile: dockerfile
            volumes:
                  - /data/java-docker-container
                  - ./app
            ports:
                  - 8080:8080
            depends_on:
                  - mongo

      mongo:
            image: mongo
            container_name: mongodb
            ports:
                  - 27017:27017
            volumes:
                  - data:/data
            environment:
                  MONGO_INITDB_ROOT_USERNAME: mongo
                  MONGO_INITDB_ROOT_PASSWORD: root

      mongo-express:
            image: mongo-express
            restart: always
            ports:
                  - 8081:8081
            environment:
                  ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
                  ME_CONFIG_MONGODB_ADMINPASSWORD: root
                  ME_CONFIG_MONGODB_SERVER: mongo
volumes:
      data: {}
networks:
      default:
            name: mongodb_network
            
##version: "3.7"
##services:
##  app:
##    build: .
##    restart: always
##    ports:
##      - 8080:8080
##    links:
##      - mongo_db:app_db
##  mongo_db:
##    image: "mongo:4.4.3"
##    restart: always
##    ports:
##      - 27017:27017