version: "3"
services:
  sanjaymongodb:
    image: mongo:latest
    container_name: "sanjaymongodb"
    ports:
      - 27017:27017
    environment: 
       MONGO_INITDB_ROOT_USERNAME: mongo
       MONGO_INITDB_ROOT_PASSWORD: root
       MONGO_INITDB: admin
    restart: always
    volumes:
      - /home/data/db:/data/db
  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mongodb
#    build:
#         context: .
#         dockerfile: dockerfile
    ports:
      - 8080:8080
    links:
      - sanjaymongodb